# -*- coding: utf-8 -*-
"""Untitled18.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1A2fkj8iiKR4tnLI_6LWvQR2HiVPDcgF2
"""
from keras.models import load_model

import yfinance as yf
import streamlit as st
st.title("Stock Trend Prediction")
user_input=st.text_input("Enter Strock Ticker","GOOG")
start="2018-01-01"
end="2022-01-01"
df=yf.download(user_input,start,end)
st.subheader('Data from 2018-2020')
st.write(df.describe())